name: Deploy to Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to Server 1
      run: |
        echo "Deploying to Server 1"
        scp -r html/* ubuntu@54.162.52.230:/home/ubuntu/html
